//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public string AdSoyad { get; set; }
        public string TC { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
    }
}
